config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'dashboard#index'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/lesson_word.rb
class LessonWord < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :word_answer
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def add_role(role_object)
    self.user_roles.create(role: role_object)
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
end

app/models/word_answer.rb
class WordAnswer < ApplicationRecord
  belongs_to :word
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def index
    render "layouts/application"
  end
  
  def authenticate
    redirect_to login_path unless logged_in?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate

  def index
    render 'dashboard/index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'sessions/new'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:new] 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      render 'dashboard/index'
    else
      render 'users/new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in_user
    @logged_in_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !logged_in_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @logged_in_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<% content_for :page do %>dashboard<% end %>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="avatar">
                    <img class="img-responsive" src="http://placehold.it/350x150">
                </div>
                <div class="text-center">
                    <h4><%= logged_in_user.name =%></h4>
                    <h5><%= logged_in_user.email =%></h5>
                </div>
                <ul class="list-group no-side-border">
                    <li class="list-group-item"><a href="#">Users</a></li>
                    <li class="list-group-item"><a href="#">Categories</a></li>
                    <li class="list-group-item"><a href="#">Word list</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <h1 class="panel-heading title">Activities</h1>
            <div class="panel-body">
                <div class="well">
                    <div class="row">
                        <div class="col-md-9">You followed <a href="#">John Doe</a></div>
                        <div class="col-md-3 text-right">April 01, 2017</div>
                    </div>
                </div>
                <div class="well">
                    <div class="row">
                        <div class="col-md-9"><a href="#">John Doe</a> learned 20 words in <a href="#">Home Words</a></div>
                        <div class="col-md-3 text-right">April 01, 2017</div>
                    </div>
                </div>
                <div class="well">
                    <div class="row">
                        <div class="col-md-9"><a href="#">John Doe</a> learned 10 words in <a href="#">Park Words</a></div>
                        <div class="col-md-3 text-right">April 01, 2017</div>
                    </div>
                </div>
                <div class="well">
                    <div class="row">
                        <div class="col-md-9">You learned 10 words in <a href="#">Park Words</a></div>
                        <div class="col-md-3 text-right">April 01, 2017</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FphFelsRor1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/partials/header' %>
      <div class="container">
        <div class="main-content <%= yield :page %>-page">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Framgia E-learning', root_path, class: "navbar-brand" =%>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to 'Settings', '#' =%></li>
                <li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
                <% else %>
                <li><%= link_to 'Login', login_path =%></li>
                <li><%= link_to 'Sign Up', signup_path %></li>
                <% end %>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= form_for(@user, url:signup_path, :html => {:class => 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'col-sm-2 col-sm-offset-3' %>
    <div class="col-sm-3"><%= f.text_field :name, :class => 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => 'col-sm-2 col-sm-offset-3' %>
    <div class="col-sm-3"><%= f.email_field :email, :class => 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :password, :class => 'col-sm-2 col-sm-offset-3' %>
    <div class="col-sm-3"><%= f.password_field :password, :class => 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirmation", :class => 'col-sm-2 col-sm-offset-3' %>
    <div class="col-sm-3"><%= f.password_field :password_confirmation, :class => 'form-control' %></div>
  </div>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-center">
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editing User</h3>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Users</h3>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% content_for :page do %>login<% end %>

<h1 class="title">New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>